### ISSUE TITLE
DATABASE_URL is not set.

### ISSUE THREAD

**Issue by trsteel88** [symfonycorp/platformsh-symfony-template#21]
Hi,

https://github.com/platformsh/symfonyflex-bridge has been abandoned and neither that or this repository explains how to automatically set the DATABASE_URL.

Is there a way to automate this or does this need to be manually set somewhere?

**Comment by trsteel88** [comment]
Apologies, the URL on the other repository was dead but it looks like it has just started working. I'm guessing it has only just been published.

I will read the docs and close this for now.

**Comment by fabpot** [comment]
It is setup automatically for you.
But only if you have this line in your build hook: https://github.com/symfonycorp/platformsh-symfony-template/blob/6.2/.platform.app.yaml#L47
I agree that the currents docs at https://symfony.com/doc/current/cloud/env.html are not clear about this. I will update this ASAP.

**Comment by trsteel88** [comment]
Hey @fabpot, thanks for the quick response. I already have this line but it still fails.

```
W: + symfony composer install --prefer-dist --optimize-autoloader --apcu-autoloader --classmap-authoritative --no-progress --no-ansi --no-interaction
          W: Installing dependencies from lock file
          W: Verifying lock file contents can be installed on current platform.
          W: Nothing to install, update or remove
          W: Generating optimized autoload files
          W: 81 packages you are using are looking for funding.
          W: Use the `composer fund` command to find out more!
          W: 
          W: Run composer recipes at any time to see the status of your Symfony recipes.
          W: 
          W: Executing script cache:clear [KO]
          W:  [KO]
          W: Script cache:clear returned with error code 255
          W: !!  
          W: !!  In ExceptionConverter.php line 101:
          W: !!                                                                                 
          W: !!    An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or  
          W: !!     directory                                                                   
          W: !!                                                                                 
          W: !!  
          W: !!  In Exception.php line 28:
          W: !!                                                      
          W: !!    SQLSTATE[HY000] [2002] No such file or directory  
          W: !!                                                      
          W: !!  
          W: !!  In Driver.php line 34:
          W: !!                                                      
          W: !!    SQLSTATE[HY000] [2002] No such file or directory  
          W: !!                                                      
          W: !!  
          W: !!  
          W: Script @auto-scripts was called via post-install-cmd
          W: unable to run /app/.global/bin/composer2 install --prefer-dist --optimize-autoloader --apcu-autoloader --classmap-authoritative --no-progress --no-ansi --no-interaction
        
        E: Error building project: Step failed with status code 255.

      E: Error: Unable to build application, aborting.
```

**Comment by trsteel88** [comment]
@fabpot is there any kind of changelog to follow on that configurator script by the way?

I am all of a sudden seeing the following errors and I'm not sure if it's because something has changed in that bash script.

```
[01-Apr-2023 14:27:54 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/app/var/cache/prod/twig/00/00473e3471dba530b546d5f0e433c716.php' (include_path='.:') in /app/var/cache/prod/App_KernelProdContainer.preload.php:1346
```

**Comment by trsteel88** [comment]
@fabpot I'm still having the same problem with this even on a brand new project on psh. I am still having to require platformsh/symfonyflex-bridge even though I'm using https://get.symfony.com/cloud/configurator

Is there anything special that needs to be done to make this work?

**Comment by fabpot** [comment]
Can you ping me on Slack to figure that out together?

**Comment by trsteel88** [comment]
This has been resolved (Thanks for the help @fabpot).

For anyone having a similar issue, platform.sh does not have access to the database during the build step. I had not specified the serverVersion within the Doctrine configuration so it was trying to access the database to determine this automatically.

I needed to specify the server version for Doctrine so it would not attempt to read this from the database.

Old .env:
```
DATABASE_URL="mysql://db_user:db_password@localhost:3306/db_name?charset=utf8mb4"
```

New .env
```
DATABASE_URL="mysql://db_user:db_password@localhost:3306/db_name?serverVersion=mariadb-10.6.0&charset=utf8mb4"
```

**Comment by lecrapal** [comment]
I still have the same error even if i add the serverVersion.
It seems like symfony-build keeps trying to connect to the database.
This behaviour came after I've installed stimulus, turbo-ux and ux-autocomplete Here's my composer.
```
{
    "type": "project",
    "license": "proprietary",
    "minimum-stability": "stable",
    "prefer-stable": true,
    "require": {
        "php": ">=8.1",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "blackfireio/blackfire-symfony-meta": "^1.0",
        "doctrine/annotations": "^2.0",
        "doctrine/doctrine-bundle": "^2.9",
        "doctrine/doctrine-migrations-bundle": "^3.2",
        "doctrine/orm": "^2.15",
        "phpdocumentor/reflection-docblock": "^5.3",
        "phpstan/phpdoc-parser": "^1.21",
        "symfony/asset": "6.3.*",
        "symfony/console": "6.3.*",
        "symfony/doctrine-messenger": "6.3.*",
        "symfony/dotenv": "6.3.*",
        "symfony/expression-language": "6.3.*",
        "symfony/flex": "^2",
        "symfony/form": "6.3.*",
        "symfony/framework-bundle": "6.3.*",
        "symfony/http-client": "6.3.*",
        "symfony/intl": "6.3.*",
        "symfony/mailer": "6.3.*",
        "symfony/mime": "6.3.*",
        "symfony/monolog-bundle": "^3.0",
        "symfony/notifier": "6.3.*",
        "symfony/process": "6.3.*",
        "symfony/property-access": "6.3.*",
        "symfony/property-info": "6.3.*",
        "symfony/runtime": "6.3.*",
        "symfony/security-bundle": "6.3.*",
        "symfony/serializer": "6.3.*",
        "symfony/stimulus-bundle": "*",
        "symfony/string": "6.3.*",
        "symfony/translation": "6.3.*",
        "symfony/twig-bundle": "6.3.*",
        "symfony/ux-autocomplete": "*",
        "symfony/ux-turbo": "*",
        "symfony/validator": "6.3.*",
        "symfony/web-link": "6.3.*",
        "symfony/yaml": "6.3.*",
        "symfonycorp/platformsh-meta": "^1.0",
        "twig/extra-bundle": "^2.12|^3.0",
        "twig/twig": "^2.12|^3.0"
    },
    "config": {
        "allow-plugins": {
            "php-http/discovery": true,
            "symfony/flex": true,
            "symfony/runtime": true
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*",
        "symfony/polyfill-php73": "*",
        "symfony/polyfill-php74": "*",
        "symfony/polyfill-php80": "*",
        "symfony/polyfill-php81": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "6.3.*"
        }
    },
    "require-dev": {
        "phpunit/phpunit": "^9.5",
        "symfony/browser-kit": "6.3.*",
        "symfony/css-selector": "6.3.*",
        "symfony/debug-bundle": "6.3.*",
        "symfony/maker-bundle": "^1.0",
        "symfony/phpunit-bridge": "^6.3",
        "symfony/stopwatch": "6.3.*",
        "symfony/web-profiler-bundle": "6.3.*"
    }
}

```
